setwd("/Curso-ML/Assignment-3/")

data2y <- read.csv("transactions-2.csv") ## Items
data0y1 <- select(data2y,fraud,sex,age,income1,same_city,same_count,seller_sco,dispersao,type,V11,V12,V12.1)
print(data0y2)
##### end of normalizing
str(data0y1)
summary(data0y1)
df2 <- data.frame(fraud=0,total=0,percentage=0,pontos = 0        , incomemean = 0,city=0,count=0,seller=0,disper=0,type=0,V11=0,V12=0)
for (i in 1:8) {
 data00y <- subset(data0y1, as.numeric(data0y1[,12]) >= i)
 summary(data00y)
 fraud1 <- summary(data00y)
 fraud2 <- as.numeric(substr(fraud1[2,1],4,9))
 fraud3 <- as.numeric(substr(fraud1[1,1],3,10))
 print(fraud2)
 mean4 <- mean(data00y[,4])
 mean5 <- mean(data00y[,5])
 mean6 <- mean(data00y[,6])
 mean7 <- mean(data00y[,7])
 mean8 <- mean(data00y[,8])
 mean9 <- mean(data00y[,9])
 mean10 <- mean(data00y[,10])
 mean11 <- mean(data00y[,11])
 print(i)
 df2 <- rbind(df2, data.frame(fraud=fraud2,total= fraud3,percentage=(fraud2/fraud3),pontos=i,incomemean = mean4,city=mean5,count=mean6,seller=mean7,disper=mean8,type=mean9,V11=mean10,V12=mean11) )
}
print(df2)
summary(df2)
variables1 <- df2[3:11]
summary(variables1)
library(corrplot)
cor.test(variables1$pontos, variables1$city)
cor.test(variables1$pontos, variables1$disper)
forcorrplot <-cor(variables1)
corrplot(forcorrplot)
corrplot(forcorrplot, method = "square")
corrplot(forcorrplot, upper="number", lower="color", order="hclust")
corrplot(forcorrplot, method="number",order="hclust" )